package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// gen 이 생성 폴더에 .cs 를 만든다. 두 번 돌려도 내용이 같다 (T7).
func TestGenWritesFiles(t *testing.T) {
	out := filepath.Join(t.TempDir(), "Generated")
	if code := run([]string{"gen", "--data", okDataDir, "--out", out}); code != exitOK {
		t.Fatalf("gen 이 종료 0 이 아니다: %d", code)
	}

	// 생성물 여섯 장 + gen 이 같이 내는 Unity 셋이다 (설계 8장).
	for _, name := range []string{
		"ItemRow.cs", "MonsterRow.cs", "DropRow.cs", "Grade.cs", "Element.cs", "GameDataTables.cs",
		"GameDataLoader.cs", "GameDataException.cs", "MyGame.Data.asmdef",
	} {
		if _, err := os.Stat(filepath.Join(out, name)); err != nil {
			t.Fatalf("%s 가 안 생겼다: %v", name, err)
		}
	}

	before := mustRead(t, filepath.Join(out, "ItemRow.cs"))
	if code := run([]string{"gen", "--data", okDataDir, "--out", out}); code != exitOK {
		t.Fatalf("두 번째 gen 이 종료 0 이 아니다: %d", code)
	}
	if after := mustRead(t, filepath.Join(out, "ItemRow.cs")); after != before {
		t.Fatalf("두 번 돌렸더니 파일이 달라졌다")
	}
}

// --json 이 written·stale 을 낸다.
func TestGenJSON(t *testing.T) {
	out := filepath.Join(t.TempDir(), "Generated")
	code, got := captureJSONOutput(t, []string{"gen", "--data", okDataDir, "--out", out, "--json"})
	if code != exitOK {
		t.Fatalf("종료 코드가 %d 다", code)
	}
	written, ok := got["written"].([]any)
	if !ok || len(written) != 9 {
		t.Fatalf("written 이 아홉 장이 아니다: %#v", got["written"])
	}
	if stale, ok := got["stale"].([]any); !ok || len(stale) != 0 {
		t.Fatalf("처음 돌렸는데 stale 이 있다: %#v", got["stale"])
	}
}

// 스키마에서 표를 없앴을 때 남는 생성 파일은 지우지 않고 알리기만 한다 (설계 8장).
func TestGenReportsStale(t *testing.T) {
	out := filepath.Join(t.TempDir(), "Generated")
	if code := run([]string{"gen", "--data", okDataDir, "--out", out}); code != exitOK {
		t.Fatalf("gen 이 종료 0 이 아니다: %d", code)
	}
	// 치환된 Unity 셋도 같이 나갔는지 — Officina. 이 한 글자도 남으면 안 된다 (설계 8장).
	for _, name := range []string{"GameDataLoader.cs", "GameDataException.cs", "MyGame.Data.asmdef"} {
		if strings.Contains(mustRead(t, filepath.Join(out, name)), "Officina.") {
			t.Fatalf("%s 에 Officina. 이 남았다", name)
		}
	}
	old := filepath.Join(out, "OldRow.cs")
	if err := os.WriteFile(old, []byte("// <auto-generated>\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	_, got := captureJSONOutput(t, []string{"gen", "--data", okDataDir, "--out", out, "--json"})
	stale, ok := got["stale"].([]any)
	if !ok || len(stale) != 1 || stale[0] != "OldRow.cs" {
		t.Fatalf("stale 이 OldRow.cs 하나가 아니다: %#v", got["stale"])
	}
	if _, err := os.Stat(old); err != nil {
		t.Fatalf("옛 생성 파일을 지워 버렸다")
	}
}

func TestGenExitCodes(t *testing.T) {
	missing := filepath.Join(t.TempDir(), "없는폴더")
	if code := run([]string{"gen", "--data", missing}); code != exitReadFail {
		t.Fatalf("없는 폴더가 종료 4 가 아니다: %d", code)
	}
	if code := run([]string{"gen", "--data", okDataDir, "--wat"}); code != exitUsage {
		t.Fatalf("모르는 인자가 종료 1 이 아니다: %d", code)
	}
}

// gen 도 먼저 validate 다. 걸리면 종료 2 이고 .cs 가 한 장도 안 생긴다.
func TestGenStopsOnInvalidData(t *testing.T) {
	dir := validateCaseDir(t, "v6-ref")
	out := filepath.Join(t.TempDir(), "Generated")

	if code := run([]string{"gen", "--data", dir, "--out", out}); code != exitData {
		t.Fatalf("검증 실패 데이터가 종료 2 가 아니다: %d", code)
	}
	if entries, err := os.ReadDir(out); err == nil && len(entries) > 0 {
		t.Fatalf("검증에 걸렸는데 %d장을 썼다", len(entries))
	}
}

// schemaWith 는 ok 자료를 임시 폴더에 깔고 schema.json 만 손본다.
func schemaWith(t *testing.T, replace func(string) string) string {
	t.Helper()
	dir := copyDir(t, okDataDir)
	path := filepath.Join(dir, "schema.json")
	if err := os.WriteFile(path, []byte(replace(mustRead(t, path))), 0o644); err != nil {
		t.Fatal(err)
	}
	return dir
}

// 네임스페이스에 Officina. 이 들어 있어도 한 번만 박힌다 (리뷰 D7).
// 예전에는 생성 뒤에 한 번 더 치환해서 Studio.Studio.Officina.Data 가 나왔다.
func TestGenNamespaceContainingOfficina(t *testing.T) {
	dir := schemaWith(t, func(src string) string {
		return strings.Replace(src, `"namespace": "MyGame.Data"`, `"namespace": "Studio.Officina.Data"`, 1)
	})
	out := filepath.Join(t.TempDir(), "Generated")
	if code := run([]string{"gen", "--data", dir, "--out", out}); code != exitOK {
		t.Fatalf("gen 이 종료 0 이 아니다: %d", code)
	}
	for _, name := range []string{"ItemRow.cs", "GameDataLoader.cs", "Studio.Officina.Data.asmdef"} {
		got := mustRead(t, filepath.Join(out, name))
		if strings.Contains(got, "Studio.Studio") {
			t.Errorf("%s 에 이중 치환이 났다", name)
		}
		if !strings.Contains(got, "Studio.Officina.Data") {
			t.Errorf("%s 에 네임스페이스가 안 박혔다", name)
		}
	}
}

// 열 설명에 Officina. 이 들어 있어도 막히지 않는다 (리뷰 D7). 설명은 주석일 뿐이다.
func TestGenAllowsOfficinaInDesc(t *testing.T) {
	dir := schemaWith(t, func(src string) string {
		return strings.Replace(src, `{ "name": "atk",    "type": "int",`,
			`{ "name": "atk",    "type": "int", "desc": "Officina.Hubs 의 공격력과 같다",`, 1)
	})
	out := filepath.Join(t.TempDir(), "Generated")
	if code := run([]string{"gen", "--data", dir, "--out", out}); code != exitOK {
		t.Fatalf("설명에 Officina. 이 있다고 막혔다: 종료 %d", code)
	}
	if !strings.Contains(mustRead(t, filepath.Join(out, "ItemRow.cs")), "Officina.Hubs") {
		t.Error("열 설명이 주석으로 안 나왔다")
	}
}
